### ISSUE TITLE
Replace OLPC 'cjson' with sane canonical JSON definition

### ISSUE THREAD

**Issue by cajun-rat** [advancedtelematic/tuf-test-vectors#42]
The canonical JSON encoding used at the moment uses the OLPC Canonical JSON definition (`from securesystemslib.formats import encode_canonical as cjson`) 

This is 'interesting' because the output isn't actually JSON at all. For example:

    # from securesystemslib.formats import encode_canonical as cjson
    # print (cjson({'foo':'\n'}))
    {"foo":"
    "}
    # print (repr(cjson({'foo':'wtf\nisthis'})))
    '{"foo":"wtf\nisthis"}'

It would be _much_ nicer if this was changed to something that was also valid JSON, e.g. "JSON, with no whitespace, the keys in alphabetic order and no floats".

**Comment by heartsucker** [comment]
Related discusion: https://github.com/theupdateframework/tuf/issues/457

**Comment by heartsucker** [comment]
closed by 54d159d
