### ISSUE TITLE
Migrate away from pycrypto

### ISSUE THREAD

**Issue by zabbal** [advancedtelematic/tuf-test-vectors#60]
https://github.com/dlitz/pycrypto/issues/238 - it's officially dead and we should use https://github.com/Legrandin/pycryptodome https://pypi.org/project/pycryptodomex/ or https://pypi.python.org/pypi/cryptography module

**Comment by patrickvacek** [comment]
Indeed. Want to make the change? :) Otherwise, can you make a tech debt task to make the change?

**Comment by zabbal** [comment]
It's hardly a pressing issue - I'll make tech debt task to make sure it won't get lost.

**Comment by zabbal** [comment]
https://github.com/advancedtelematic/tuf-test-vectors/pull/61 - turns out it's rather trivial in our case. Unless I miss smth and it broke aktualizr tests. Can you double-check if it's still working for you?
